version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./music:/app/../music
      - ./images:/app/../images

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf